version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - app_network

  redis:
    image: redis:7.0
    container_name: redis_container
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app_network